"""Add default dimensions to shipment profiles

Revision ID: 0ac0fcf02e1a
Revises: e158d1c46495
Create Date: 2025-09-25 23:47:44.405091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac0fcf02e1a'
down_revision: Union[str, Sequence[str], None] = 'e158d1c46495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment_profiles', sa.Column('default_parcels', sa.Integer(), nullable=True))
    op.add_column('shipment_profiles', sa.Column('default_weight_kg', sa.Float(), nullable=True))
    op.add_column('shipment_profiles', sa.Column('default_width_cm', sa.Integer(), nullable=True))
    op.add_column('shipment_profiles', sa.Column('default_height_cm', sa.Integer(), nullable=True))
    op.add_column('shipment_profiles', sa.Column('default_length_cm', sa.Integer(), nullable=True))
    op.add_column('shipment_profiles', sa.Column('content_template', sa.String(length=255), nullable=True))
    op.add_column('shipment_profiles', sa.Column('default_service_id', sa.Integer(), nullable=True))
    op.add_column('shipment_profiles', sa.Column('default_payer', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipment_profiles', 'default_payer')
    op.drop_column('shipment_profiles', 'default_service_id')
    op.drop_column('shipment_profiles', 'content_template')
    op.drop_column('shipment_profiles', 'default_length_cm')
    op.drop_column('shipment_profiles', 'default_height_cm')
    op.drop_column('shipment_profiles', 'default_width_cm')
    op.drop_column('shipment_profiles', 'default_weight_kg')
    op.drop_column('shipment_profiles', 'default_parcels')
    # ### end Alembic commands ###
