"""Refine ShipmentProfile model for template logic

Revision ID: 20aa754d88ae
Revises: b080935f068c
Create Date: 2025-09-25 22:15:41.307008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20aa754d88ae'
down_revision: Union[str, Sequence[str], None] = 'b080935f068c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment_profiles', sa.Column('content_template', sa.String(length=255), nullable=True))
    op.add_column('shipment_profiles', sa.Column('default_payer', sa.String(length=32), nullable=True))
    op.add_column('shipment_profiles', sa.Column('default_paper_size', sa.String(length=16), nullable=True))
    op.add_column('shipment_profiles', sa.Column('default_saturday_delivery', sa.Boolean(), nullable=True))
    op.add_column('shipment_profiles', sa.Column('default_include_shipping_in_cod', sa.Boolean(), nullable=True))
    op.drop_column('shipment_profiles', 'parcels')
    op.drop_column('shipment_profiles', 'observations')
    op.drop_column('shipment_profiles', 'is_default')
    op.drop_column('shipment_profiles', 'shipment_content')
    op.drop_column('shipment_profiles', 'weight_kg')
    op.drop_column('shipment_profiles', 'service')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment_profiles', sa.Column('service', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('shipment_profiles', sa.Column('weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('shipment_profiles', sa.Column('shipment_content', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('shipment_profiles', sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('shipment_profiles', sa.Column('observations', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('shipment_profiles', sa.Column('parcels', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('shipment_profiles', 'default_include_shipping_in_cod')
    op.drop_column('shipment_profiles', 'default_saturday_delivery')
    op.drop_column('shipment_profiles', 'default_paper_size')
    op.drop_column('shipment_profiles', 'default_payer')
    op.drop_column('shipment_profiles', 'content_template')
    # ### end Alembic commands ###
