"""Add api_version to Store model

Revision ID: cdc65724512d
Revises: 
Create Date: 2025-09-13 23:48:35.432296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc65724512d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('api_version', sa.String(length=32), nullable=False, server_default='2025-07'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'api_version')
    op.drop_index(op.f('ix_orders_derived_status'), table_name='orders')
    # ### end Alembic commands ###
