"""Revert ShipmentProfile to use JSONB for DPD payload

Revision ID: e158d1c46495
Revises: 20aa754d88ae
Create Date: 2025-09-25 22:32:49.103625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e158d1c46495'
down_revision: Union[str, Sequence[str], None] = '20aa754d88ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment_profiles', sa.Column('dpd_payload_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('shipment_profiles', 'default_paper_size')
    op.drop_column('shipment_profiles', 'default_include_shipping_in_cod')
    op.drop_column('shipment_profiles', 'default_payer')
    op.drop_column('shipment_profiles', 'default_saturday_delivery')
    op.drop_column('shipment_profiles', 'content_template')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment_profiles', sa.Column('content_template', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('shipment_profiles', sa.Column('default_saturday_delivery', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('shipment_profiles', sa.Column('default_payer', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('shipment_profiles', sa.Column('default_include_shipping_in_cod', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('shipment_profiles', sa.Column('default_paper_size', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.drop_column('shipment_profiles', 'dpd_payload_template')
    # ### end Alembic commands ###
